import 'dotenv/config';
import crypto from 'node:crypto';
import pg from 'pg';

const { Pool } = pg;
const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
  max: 3,
  idleTimeoutMillis: 30000,
  connectionTimeoutMillis: 10000,
  ssl: process.env.DATABASE_SSL === 'false' ? false : { rejectUnauthorized: false }
});

const POSTGRES_SCHEMA = `
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  password_salt TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS businesses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  sector TEXT NOT NULL,
  city TEXT NOT NULL,
  currency TEXT NOT NULL DEFAULT 'IDR'
);
CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id BIGINT NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  price BIGINT NOT NULL DEFAULT 0,
  active INTEGER NOT NULL DEFAULT 1
);
CREATE TABLE IF NOT EXISTS sales (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id BIGINT NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES products(id) ON DELETE SET NULL,
  sold_on TEXT NOT NULL,
  units INTEGER NOT NULL,
  revenue BIGINT NOT NULL
);
CREATE TABLE IF NOT EXISTS trend_signals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id BIGINT NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,
  keyword TEXT NOT NULL,
  source TEXT NOT NULL,
  signal_type TEXT NOT NULL,
  growth DOUBLE PRECISION NOT NULL DEFAULT 0,
  sentiment DOUBLE PRECISION NOT NULL DEFAULT 0,
  persistence DOUBLE PRECISION NOT NULL DEFAULT 0,
  mentions INTEGER NOT NULL DEFAULT 0,
  searches INTEGER NOT NULL DEFAULT 0,
  captured_on TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS trends (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id BIGINT NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,
  keyword TEXT NOT NULL,
  category TEXT NOT NULL,
  score DOUBLE PRECISION NOT NULL,
  status TEXT NOT NULL,
  evidence TEXT NOT NULL,
  recommended_action TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (business_id, keyword)
);
CREATE TABLE IF NOT EXISTS recommendations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id BIGINT NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,
  trend_id BIGINT REFERENCES trends(id) ON DELETE SET NULL,
  title TEXT NOT NULL,
  rationale TEXT NOT NULL,
  priority TEXT NOT NULL,
  action TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  status TEXT NOT NULL DEFAULT 'open'
);
CREATE TABLE IF NOT EXISTS experiments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id BIGINT NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,
  trend_id BIGINT REFERENCES trends(id) ON DELETE SET NULL,
  product_name TEXT NOT NULL,
  hypothesis TEXT NOT NULL,
  budget BIGINT NOT NULL DEFAULT 0,
  test_days INTEGER NOT NULL DEFAULT 7,
  target_units INTEGER NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'planned',
  result_notes TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS sessions (
  token_hash TEXT PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  expires_at BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_business_user ON businesses(user_id);
CREATE INDEX IF NOT EXISTS idx_sales_business_date ON sales(business_id, sold_on);
CREATE INDEX IF NOT EXISTS idx_signals_business_keyword ON trend_signals(business_id, keyword);
CREATE INDEX IF NOT EXISTS idx_trends_business_score ON trends(business_id, score DESC);
`;


function toPg(sql) {
  let i = 0;
  return sql.replace(/\?/g, () => `$${++i}`);
}

async function initDb() {
  if (!process.env.DATABASE_URL) throw new Error('DATABASE_URL is not configured');
  await pool.query(POSTGRES_SCHEMA);
}

async function all(sql, params = []) {
  return (await pool.query(toPg(sql), params)).rows;
}

async function one(sql, params = []) {
  return (await pool.query(toPg(sql), params)).rows[0] || null;
}

async function exec(sql, params = []) {
  return await pool.query(toPg(sql), params);
}

async function insertId(sql, params = []) {
  const clean = sql.trim().replace(/;$/, '') + ' RETURNING id';
  const row = (await pool.query(toPg(clean), params)).rows[0];
  return Number(row.id);
}

function addDays(date, offset) {
  const d = new Date(date);
  d.setUTCDate(d.getUTCDate() + offset);
  return d.toISOString().slice(0, 10);
}

function today() {
  return new Date().toISOString().slice(0, 10);
}

function hashToken(token) {
  return crypto.createHash('sha256').update(token).digest('hex');
}

function makePassword(password) {
  const salt = crypto.randomBytes(16).toString('hex');
  const hash = crypto.scryptSync(password, salt, 64).toString('hex');
  return { salt, hash };
}

function verifyPassword(password, user) {
  try {
    const candidate = crypto.scryptSync(password, user.password_salt, 64);
    return crypto.timingSafeEqual(candidate, Buffer.from(user.password_hash, 'hex'));
  } catch {
    return false;
  }
}

async function createStarterData(businessId) {
  const products = [
    ['Kimpul Latte', 'Beverage', 22000],
    ['Kimpul Crispy', 'Snack', 18000],
    ['Matcha Latte', 'Beverage', 24000]
  ];
  const productIds = {};
  for (const [name, category, price] of products) {
    productIds[name] = await insertId('INSERT INTO products (business_id,name,category,price) VALUES (?,?,?,?)', [businessId, name, category, price]);
  }
  const p1 = productIds['Kimpul Latte'];
  const p2 = productIds['Kimpul Crispy'];
  const p3 = productIds['Matcha Latte'];
  const sales = [
    [p1,'2026-09-01',19,418000],[p1,'2026-09-05',22,484000],[p1,'2026-09-10',31,682000],[p1,'2026-09-15',38,836000],
    [p2,'2026-09-01',25,450000],[p2,'2026-09-05',24,432000],[p2,'2026-09-10',29,522000],[p2,'2026-09-15',35,630000],
    [p3,'2026-09-01',42,1008000],[p3,'2026-09-05',40,960000],[p3,'2026-09-10',44,1056000],[p3,'2026-09-15',43,1032000]
  ];
  for (const r of sales) await exec('INSERT INTO sales (business_id,product_id,sold_on,units,revenue) VALUES (?,?,?,?,?)', [businessId, ...r]);
  const signals = [
    ['kimpul','TikTok','social',82,0.74,77,1840,0],
    ['kimpul','Google','search',64,0.69,72,0,9800],
    ['kimpul','News','news',41,0.81,70,92,0],
    ['matcha','Instagram','social',18,0.76,63,710,0],
    ['matcha','Google','search',14,0.71,68,5400,0],
    ['seaweed','TikTok','social',79,0.32,24,650,0]
  ];
  for (const r of signals) await exec('INSERT INTO trend_signals (business_id,keyword,source,signal_type,growth,sentiment,persistence,mentions,searches,captured_on) VALUES (?,?,?,?,?,?,?,?,?,?)', [businessId, ...r, today()]);
}

async function seedDemo() {
  const exists = await one('SELECT id FROM users WHERE email=?', ['demo@trendova.id']);
  if (exists) return;
  const password = makePassword('trendova123');
  const userId = await insertId('INSERT INTO users (name,email,password_hash,password_salt) VALUES (?,?,?,?)', ['Demo Owner','demo@trendova.id',password.hash,password.salt]);
  const businessId = await insertId('INSERT INTO businesses (user_id,name,sector,city) VALUES (?,?,?,?)', [userId,'Kimpul & Co. F&B','Food & Beverage','Yogyakarta']);
  await createStarterData(businessId);
  await recomputeTrends(businessId);
  await seedRecommendations(businessId);
}

function parseCookies(req) {
  const raw = req.headers.cookie || '';
  const out = {};
  for (const part of raw.split(';')) {
    const [k, ...rest] = part.trim().split('=');
    if (k) out[k] = decodeURIComponent(rest.join('='));
  }
  return out;
}

async function sessionUser(req) {
  const token = parseCookies(req).trendova_session;
  if (!token) return null;
  const s = await one('SELECT s.user_id, s.expires_at, u.id, u.name, u.email FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=?', [hashToken(token)]);
  if (!s) return null;
  if (Date.now() > Number(s.expires_at)) {
    await exec('DELETE FROM sessions WHERE token_hash=?', [hashToken(token)]);
    return null;
  }
  return { id: Number(s.id), name: s.name, email: s.email };
}

async function requireUser(req, res) {
  const user = await sessionUser(req);
  if (!user) {
    sendJson(res, 401, { error: 'Unauthenticated' });
    return null;
  }
  return user;
}

async function businessForUser(userId) {
  return await one('SELECT * FROM businesses WHERE user_id=? ORDER BY id LIMIT 1', [userId]);
}

function sendJson(res, status, data, extraHeaders = {}) {
  const body = JSON.stringify(data);
  res.writeHead(status, {
    'Content-Type': 'application/json; charset=utf-8',
    'Cache-Control': 'no-store',
    ...extraHeaders
  });
  res.end(body);
}

function sendText(res, status, text, contentType = 'text/plain; charset=utf-8') {
  res.writeHead(status, { 'Content-Type': contentType });
  res.end(text);
}

function bodyJson(req) {
  return new Promise((resolve, reject) => {
    let raw = '';
    req.on('data', chunk => {
      raw += chunk;
      if (raw.length > 1_000_000) {
        req.destroy();
        reject(new Error('Payload too large'));
      }
    });
    req.on('end', () => {
      try { resolve(raw ? JSON.parse(raw) : {}); }
      catch (err) { reject(err); }
    });
    req.on('error', reject);
  });
}

async function salesMomentum(businessId, keyword) {
  const products = await all('SELECT id,name FROM products WHERE business_id=? AND lower(name) LIKE ?', [businessId, `%${keyword.toLowerCase()}%`]);
  if (!products.length) return 0;
  const ids = products.map(p => Number(p.id));
  const recentFrom = addDays(new Date(), -10);
  const previousFrom = addDays(new Date(), -30);
  let recent = 0, previous = 0;
  for (const id of ids) {
    recent += Number((await one('SELECT COALESCE(SUM(units),0) units FROM sales WHERE business_id=? AND product_id=? AND sold_on>=?', [businessId,id,recentFrom]))?.units || 0);
    previous += Number((await one('SELECT COALESCE(SUM(units),0) units FROM sales WHERE business_id=? AND product_id=? AND sold_on<? AND sold_on>=?', [businessId,id,recentFrom,previousFrom]))?.units || 0);
  }
  if (!previous) return recent ? 10 : 0;
  const growth = (recent - previous) / previous;
  return Math.max(-5, Math.min(10, growth * 10));
}

async function recomputeTrends(businessId) {
  const signals = await all(`SELECT keyword,
    AVG(growth) growth, AVG(sentiment) sentiment, AVG(persistence) persistence,
    SUM(mentions) mentions, SUM(searches) searches,
    COUNT(DISTINCT source) sources
    FROM trend_signals WHERE business_id=? GROUP BY keyword`, [businessId]);
  for (const s of signals) {
    const salesBoost = await salesMomentum(businessId, s.keyword);
    const cross = Math.min(20, (Number(s.sources) / 3) * 20);
    const growth = Math.min(35, Math.max(0, Number(s.growth) / 100 * 35));
    const sent = Math.min(10, Math.max(0, ((Number(s.sentiment) + 1) / 2) * 10));
    const persistence = Math.min(15, Math.max(0, Number(s.persistence) / 100 * 15));
    const score = Math.round((growth + cross + sent + persistence + salesBoost) * 10) / 10;
    const status = score >= 65 ? 'Emerging Opportunity' : score >= 50 ? 'Watch' : 'Noise Risk';
    const evidence = `${Number(s.sources)} sumber, pertumbuhan ${Math.round(Number(s.growth))}%, persistence ${Math.round(Number(s.persistence))}%, sentiment ${Math.round(Number(s.sentiment)*100)}%${salesBoost ? `, sales momentum +${Math.round(salesBoost)} poin` : ''}`;
    const category = s.keyword === 'kimpul' ? 'Local Ingredient' : s.keyword === 'matcha' ? 'Beverage' : 'Emerging Signal';
    const action = status === 'Emerging Opportunity'
      ? `Jalankan eksperimen terbatas untuk ${s.keyword}`
      : status === 'Watch'
        ? `Pantau ${s.keyword} 7 hari dan validasi sumber tambahan`
        : `Jangan jadikan ${s.keyword} sebagai dasar produksi massal`;
    const existing = await one('SELECT id FROM trends WHERE business_id=? AND keyword=?', [businessId,s.keyword]);
    if (existing) {
      await exec('UPDATE trends SET category=?,score=?,status=?,evidence=?,recommended_action=?,updated_at=? WHERE id=?', [category,score,status,evidence,action,new Date().toISOString(),existing.id]);
    } else {
      await exec('INSERT INTO trends (business_id,keyword,category,score,status,evidence,recommended_action) VALUES (?,?,?,?,?,?,?)', [businessId,s.keyword,category,score,status,evidence,action]);
    }
  }
}

async function seedRecommendations(businessId) {
  const trends = await all('SELECT * FROM trends WHERE business_id=? ORDER BY score DESC LIMIT 5', [businessId]);
  for (const t of trends) {
    const exists = await one('SELECT id FROM recommendations WHERE business_id=? AND trend_id=?', [businessId,t.id]);
    if (exists) continue;
    await exec('INSERT INTO recommendations (business_id,trend_id,title,rationale,priority,action) VALUES (?,?,?,?,?,?)', [
      businessId, t.id, `Eksperimen ${t.keyword}`, `${t.evidence}. Uji secara terbatas sebelum keputusan produksi yang lebih besar.`, Number(t.score)>=65?'high':'medium', t.recommended_action
    ]);
  }
}

async function latestDashboard(b) {
  await recomputeTrends(b.id);
  const trends = await all('SELECT * FROM trends WHERE business_id=? ORDER BY score DESC', [b.id]);
  const top = trends[0] || null;
  const from30 = addDays(new Date(), -30);
  const totalRevenue = Number((await one('SELECT COALESCE(SUM(revenue),0) revenue FROM sales WHERE business_id=? AND sold_on>=?', [b.id,from30]))?.revenue || 0);
  const totalUnits = Number((await one('SELECT COALESCE(SUM(units),0) units FROM sales WHERE business_id=? AND sold_on>=?', [b.id,from30]))?.units || 0);
  const activeOpps = trends.filter(t => t.status === 'Emerging Opportunity').length;
  const openRec = Number((await one("SELECT COUNT(*) c FROM recommendations WHERE business_id=? AND status='open'", [b.id]))?.c || 0);
  return { business:b, metrics:{activeOpps,openRec,totalRevenue,totalUnits}, topTrend:top, trends:trends.slice(0,5) };
}



let dbReady = null;

async function ensureDatabase() {
  if (!dbReady) {
    dbReady = initDb().then(() => seedDemo()).catch(err => {
      dbReady = null;
      throw err;
    });
  }
  await dbReady;
}

export async function handleRequest(req, res) {
  await ensureDatabase();
  const url = new URL(req.url, `http://${req.headers.host || 'localhost'}`);
  try {
    if (url.pathname === '/api/health') return sendJson(res,200,{ok:true,service:'trendova',database:'postgres',time:new Date().toISOString()});

    if (url.pathname === '/api/auth/register' && req.method === 'POST') {
      const body = await bodyJson(req);
      const name = String(body.name || '').trim();
      const email = String(body.email || '').trim().toLowerCase();
      const password = String(body.password || '');
      const businessName = String(body.businessName || '').trim() || `${name}'s F&B`;
      const city = String(body.city || '').trim() || 'Yogyakarta';
      if (!name || !email || !password) return sendJson(res,400,{error:'Nama, email, dan password wajib diisi.'});
      if (password.length < 8) return sendJson(res,400,{error:'Password minimal 8 karakter.'});
      if (!/^\S+@\S+\.\S+$/.test(email)) return sendJson(res,400,{error:'Format email tidak valid.'});
      const existing = await one('SELECT id FROM users WHERE email=?', [email]);
      if (existing) return sendJson(res,409,{error:'Email sudah terdaftar.'});
      const pw = makePassword(password);
      const userId = await insertId('INSERT INTO users (name,email,password_hash,password_salt) VALUES (?,?,?,?)', [name,email,pw.hash,pw.salt]);
      const businessId = await insertId('INSERT INTO businesses (user_id,name,sector,city) VALUES (?,?,?,?)', [userId,businessName,'Food & Beverage',city]);
      await createStarterData(businessId);
      await recomputeTrends(businessId);
      await seedRecommendations(businessId);
      const token = crypto.randomBytes(32).toString('hex');
      await exec('INSERT INTO sessions (token_hash,user_id,expires_at) VALUES (?,?,?)', [hashToken(token),userId,Date.now()+604800000]);
      const secure = process.env.NODE_ENV === 'production' ? '; Secure' : '';
      res.setHeader('Set-Cookie', `trendova_session=${encodeURIComponent(token)}; HttpOnly; Path=/; SameSite=Lax; Max-Age=604800${secure}`);
      return sendJson(res,201,{user:{id:userId,name,email}});
    }

    if (url.pathname === '/api/auth/login' && req.method === 'POST') {
      const body = await bodyJson(req);
      const user = await one('SELECT * FROM users WHERE email=?', [String(body.email || '').trim().toLowerCase()]);
      if (!user || !verifyPassword(String(body.password || ''), user)) return sendJson(res,401,{error:'Email atau password salah.'});
      const token = crypto.randomBytes(32).toString('hex');
      await exec('INSERT INTO sessions (token_hash,user_id,expires_at) VALUES (?,?,?)', [hashToken(token),user.id,Date.now()+604800000]);
      const secure = process.env.NODE_ENV === 'production' ? '; Secure' : '';
      res.setHeader('Set-Cookie', `trendova_session=${encodeURIComponent(token)}; HttpOnly; Path=/; SameSite=Lax; Max-Age=604800${secure}`);
      return sendJson(res,200,{user:{id:Number(user.id),name:user.name,email:user.email}});
    }

    if (url.pathname === '/api/auth/logout' && req.method === 'POST') {
      const token = parseCookies(req).trendova_session;
      if (token) await exec('DELETE FROM sessions WHERE token_hash=?', [hashToken(token)]);
      res.setHeader('Set-Cookie','trendova_session=; HttpOnly; Path=/; SameSite=Lax; Max-Age=0');
      return sendJson(res,200,{ok:true});
    }

    if (url.pathname === '/api/me' && req.method === 'GET') {
      const user = await sessionUser(req);
      return sendJson(res,user ? 200 : 401,user ? {user} : {error:'Unauthenticated'});
    }

    if (url.pathname.startsWith('/api/')) {
      const user = await requireUser(req,res);
      if (!user) return;
      const business = await businessForUser(user.id);
      if (!business) return sendJson(res,404,{error:'Business profile not found'});

      if (url.pathname === '/api/dashboard' && req.method === 'GET') return sendJson(res,200,await latestDashboard(business));
      if (url.pathname === '/api/trends' && req.method === 'GET') {
        await recomputeTrends(business.id);
        return sendJson(res,200,{trends:await all('SELECT * FROM trends WHERE business_id=? ORDER BY score DESC',[business.id])});
      }
      if (url.pathname === '/api/signals' && req.method === 'GET') return sendJson(res,200,{signals:await all('SELECT * FROM trend_signals WHERE business_id=? ORDER BY captured_on DESC,id DESC',[business.id])});
      if (url.pathname === '/api/sales' && req.method === 'GET') return sendJson(res,200,{sales:await all('SELECT s.*,p.name product_name FROM sales s LEFT JOIN products p ON p.id=s.product_id WHERE s.business_id=? ORDER BY sold_on DESC,id DESC',[business.id])});
      if (url.pathname === '/api/products' && req.method === 'GET') return sendJson(res,200,{products:await all('SELECT * FROM products WHERE business_id=? ORDER BY name',[business.id])});
      if (url.pathname === '/api/recommendations' && req.method === 'GET') {
        await recomputeTrends(business.id); await seedRecommendations(business.id);
        return sendJson(res,200,{recommendations:await all("SELECT r.*,t.keyword trend_keyword FROM recommendations r LEFT JOIN trends t ON t.id=r.trend_id WHERE r.business_id=? ORDER BY CASE r.priority WHEN 'high' THEN 1 ELSE 2 END, r.created_at DESC",[business.id])});
      }
      if (url.pathname === '/api/profile' && req.method === 'GET') return sendJson(res,200,{business});
      if (url.pathname === '/api/profile' && req.method === 'PUT') {
        const body = await bodyJson(req);
        const name = String(body.name || business.name).trim();
        const city = String(body.city || business.city).trim();
        await exec('UPDATE businesses SET name=?, city=? WHERE id=?',[name,city,business.id]);
        return sendJson(res,200,{business:await businessForUser(user.id)});
      }
      if (url.pathname === '/api/trends/analyze' && req.method === 'POST') {
        const body = await bodyJson(req);
        const keyword = String(body.keyword || '').trim().toLowerCase();
        if (!keyword) return sendJson(res,400,{error:'Keyword wajib diisi.'});
        const sources = Array.isArray(body.sources) && body.sources.length ? body.sources : ['Social Media','Search'];
        const base = Math.min(90,25 + keyword.length * 3);
        const randomish = keyword.split('').reduce((a,c) => a + c.charCodeAt(0),0) % 23;
        const growth = Math.min(95,base + randomish);
        const sentiment = Math.max(0.2,Math.min(0.95,0.55 + (randomish % 31) / 100));
        const persistence = Math.min(95,45 + (randomish % 44));
        for (const src of sources) {
          const type = src.toLowerCase().includes('search') ? 'search' : src.toLowerCase().includes('news') ? 'news' : 'social';
          await exec('INSERT INTO trend_signals (business_id,keyword,source,signal_type,growth,sentiment,persistence,mentions,searches,captured_on) VALUES (?,?,?,?,?,?,?,?,?,?)', [business.id,keyword,src,type,growth-(type==='news'?14:0),Math.min(0.99,sentiment+(type==='news'?0.05:0)),persistence,100+randomish*3,type==='search'?500+randomish*120:0,today()]);
        }
        await recomputeTrends(business.id); await seedRecommendations(business.id);
        const trend = await one('SELECT * FROM trends WHERE business_id=? AND keyword=?',[business.id,keyword]);
        return sendJson(res,200,{trend,message:'Trend recalculated from multi-source signals.'});
      }
      if (url.pathname === '/api/sales' && req.method === 'POST') {
        const body = await bodyJson(req);
        const product = await one('SELECT id,price FROM products WHERE business_id=? AND id=?',[business.id,Number(body.productId)]);
        if (!product) return sendJson(res,400,{error:'Produk tidak ditemukan.'});
        const units = Math.max(1,Number(body.units || 0));
        const revenue = Math.max(0,Number(body.revenue || Number(product.price) * units));
        await exec('INSERT INTO sales (business_id,product_id,sold_on,units,revenue) VALUES (?,?,?,?,?)',[business.id,product.id,String(body.soldOn || today()),units,revenue]);
        return sendJson(res,201,{ok:true});
      }
      if (url.pathname === '/api/recommendations' && req.method === 'PATCH') {
        const body = await bodyJson(req);
        await exec('UPDATE recommendations SET status=? WHERE business_id=? AND id=?',[body.status==='done'?'done':'open',business.id,Number(body.id)]);
        return sendJson(res,200,{ok:true});
      }
      if (url.pathname === '/api/experiments' && req.method === 'GET') return sendJson(res,200,{experiments:await all('SELECT e.*,t.keyword trend_keyword FROM experiments e LEFT JOIN trends t ON t.id=e.trend_id WHERE e.business_id=? ORDER BY created_at DESC',[business.id])});
      if (url.pathname === '/api/experiments' && req.method === 'POST') {
        const body = await bodyJson(req);
        const name = String(body.productName || '').trim();
        const hypothesis = String(body.hypothesis || '').trim();
        if (!name || !hypothesis) return sendJson(res,400,{error:'Nama produk dan hipotesis wajib diisi.'});
        const id = await insertId('INSERT INTO experiments (business_id,trend_id,product_name,hypothesis,budget,test_days,target_units) VALUES (?,?,?,?,?,?,?)',[business.id,body.trendId ? Number(body.trendId) : null,name,hypothesis,Number(body.budget || 0),Number(body.testDays || 7),Number(body.targetUnits || 0)]);
        return sendJson(res,201,{id});
      }
      if (url.pathname === '/api/products' && req.method === 'POST') {
        const body = await bodyJson(req);
        const name = String(body.name || '').trim();
        if (!name) return sendJson(res,400,{error:'Nama produk wajib diisi.'});
        const id = await insertId('INSERT INTO products (business_id,name,category,price) VALUES (?,?,?,?)',[business.id,name,String(body.category || 'Other'),Number(body.price || 0)]);
        return sendJson(res,201,{id});
      }
      return sendJson(res,404,{error:'API route not found'});
    }

    return sendJson(res,404,{error:'Not found'});
  } catch (err) {
    console.error(err);
    if (err?.code === '23505') return sendJson(res,409,{error:'Data sudah terdaftar.'});
    return sendJson(res,500,{error:'Internal server error',detail:process.env.NODE_ENV==='development' ? err.message : undefined});
  }
}
