const $ = (s) => document.querySelector(s);
const $$ = (s) => [...document.querySelectorAll(s)];
const state = { user:null, business:null, trends:[], products:[] };
const fmtIDR = n => new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(n||0));
const fmtNum = n => new Intl.NumberFormat('id-ID').format(Number(n||0));
const toast = (msg, ok=true) => { const el=document.createElement('div'); el.className=`toast ${ok?'ok':'err'}`; el.textContent=msg; $('#toast').appendChild(el); setTimeout(()=>el.remove(),3200); };
async function api(url, options={}){
  const endpoint = url;
  const r = await fetch(endpoint,{headers:{'Content-Type':'application/json',...(options.headers||{})},...options});
  let data={}; try{data=await r.json();}catch{}
  if(!r.ok) throw new Error(data.error||`Request failed (${r.status})`);
  return data;
}
function nav(view){ $$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.view===view)); $$('.view').forEach(v=>v.classList.toggle('hidden',v.id!==view)); const titles={dashboard:'Overview',trends:'Trend Radar',sales:'Sales Data',recommendations:'AI Recommendations',experiments:'Experiments',profile:'Business Profile'}; const eye={dashboard:'COMMAND CENTER',trends:'SIGNAL VALIDATION',sales:'INTERNAL DATA',recommendations:'DECISION SUPPORT',experiments:'VALIDATION LAB',profile:'BUSINESS CONTEXT'}; $('#pageTitle').textContent=titles[view]||'Overview'; $('#sectionEyebrow').textContent=eye[view]||'TRENDOVA'; if(view==='dashboard')loadDashboard(); if(view==='trends')loadTrends(); if(view==='sales')loadSales(); if(view==='recommendations')loadRecommendations(); if(view==='experiments')loadExperiments(); if(view==='profile')loadProfile(); }
$$('.nav').forEach(n=>n.addEventListener('click',()=>nav(n.dataset.view))); $$('[data-view-jump]').forEach(x=>x.addEventListener('click',()=>nav(x.dataset.viewJump)));
async function loadMe(){ try{ const d=await api('/api/me'); state.user=d.user; $('#authView').classList.add('hidden'); $('#appView').classList.remove('hidden'); $('#userName').textContent=d.user.name; $('#avatar').textContent=d.user.name.split(' ').map(x=>x[0]).slice(0,2).join('').toUpperCase(); await loadBusiness(); nav('dashboard'); } catch { $('#authView').classList.remove('hidden'); $('#appView').classList.add('hidden'); } }
async function loadBusiness(){ const d=await api('/api/profile'); state.business=d.business; $('#businessName').textContent=d.business.name; }
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();try{const d=await api('/api/auth/login',{method:'POST',body:JSON.stringify({email:$('#email').value,password:$('#password').value})});state.user=d.user;toast('Login berhasil');await loadMe();}catch(err){toast(err.message,false)}});
function setAuthMode(mode){const login=mode==='login';$('#loginForm').classList.toggle('hidden',!login);$('#registerForm').classList.toggle('hidden',login);$('#loginTab').classList.toggle('active',login);$('#registerTab').classList.toggle('active',!login);}
$('#loginTab').addEventListener('click',()=>setAuthMode('login'));
$('#registerTab').addEventListener('click',()=>setAuthMode('register'));
$('#registerForm').addEventListener('submit',async e=>{e.preventDefault();try{const d=await api('/api/auth/register',{method:'POST',body:JSON.stringify({name:$('#regName').value,email:$('#regEmail').value,password:$('#regPassword').value,businessName:$('#regBusiness').value,city:$('#regCity').value})});state.user=d.user;toast('Workspace berhasil dibuat');await loadMe();}catch(err){toast(err.message,false)}});
$('#logoutBtn').addEventListener('click',async()=>{await api('/api/auth/logout',{method:'POST'});location.reload()});
async function loadDashboard(){ const d=await api('/api/dashboard'); state.trends=d.trends; $('#kpiOpp').textContent=fmtNum(d.metrics.activeOpps); $('#kpiRec').textContent=fmtNum(d.metrics.openRec); $('#kpiRevenue').textContent=fmtIDR(d.metrics.totalRevenue); $('#kpiUnits').textContent=fmtNum(d.metrics.totalUnits); $('#heroTitle').textContent=d.topTrend?`${d.topTrend.keyword.toUpperCase()} is showing an emerging signal.`:'No strong signal yet.'; $('#heroText').textContent=d.topTrend?`${d.topTrend.evidence}. ${d.topTrend.recommended_action}.`:'Add signals to start the intelligence loop.'; $('#heroScore').textContent=d.topTrend?Math.round(d.topTrend.score):'—'; $('#trendList').innerHTML=d.trends.map(t=>`<div class="trend-item"><div><b>${t.keyword}</b><div class="meta">${t.evidence}</div></div><div><div class="score">${Math.round(t.score)}</div><span class="pill">${t.status}</span></div></div>`).join('') || '<div class="muted">No trend data.</div>'; }
function statusClass(s){return s.includes('Emerging')?'op':s==='Watch'?'watch':'noise'}
async function loadTrends(){ const [t,s]=await Promise.all([api('/api/trends'),api('/api/signals')]); state.trends=t.trends; const sourceCount={}; s.signals.forEach(x=>{sourceCount[x.keyword]=(sourceCount[x.keyword]||new Set());sourceCount[x.keyword].add(x.source)}); $('#trendTable').innerHTML=`<table class="data-table"><thead><tr><th>Keyword</th><th>Score</th><th>Status</th><th>Category</th><th>Evidence</th><th>Action</th></tr></thead><tbody>${state.trends.map(t=>`<tr><td><b>${t.keyword}</b><div class="muted">${[...(sourceCount[t.keyword]||[])].join(' · ')}</div></td><td><b>${Math.round(t.score)}</b></td><td><span class="status ${statusClass(t.status)}">${t.status}</span></td><td>${t.category}</td><td>${t.evidence}</td><td>${t.recommended_action}</td></tr>`).join('')}</tbody></table>`; populateTrendSelects(); }
$('#analyzeForm').addEventListener('submit',async e=>{e.preventDefault();const sources=$$('#analyzeForm input[type=checkbox]:checked').map(x=>x.value);try{const d=await api('/api/trends/analyze',{method:'POST',body:JSON.stringify({keyword:$('#trendKeyword').value,sources})});toast(`Signal ${d.trend.keyword} dianalisis`);$('#trendKeyword').value='';await loadTrends();}catch(err){toast(err.message,false)}});
async function loadProducts(){ const d=await api('/api/products'); state.products=d.products; $('#saleProduct').innerHTML=state.products.map(p=>`<option value="${p.id}">${p.name}</option>`).join(''); }
async function loadSales(){ await loadProducts(); const d=await api('/api/sales'); $('#salesTable').innerHTML=`<table class="data-table"><thead><tr><th>Date</th><th>Product</th><th>Units</th><th>Revenue</th></tr></thead><tbody>${d.sales.map(s=>`<tr><td>${s.sold_on}</td><td>${s.product_name||'Unlinked'}</td><td>${fmtNum(s.units)}</td><td>${fmtIDR(s.revenue)}</td></tr>`).join('')}</tbody></table>`; $('#saleDate').value=new Date().toISOString().slice(0,10); const selected=state.products[0]; if(selected) $('#saleRevenue').value=selected.price*10; }
$('#showSaleForm').addEventListener('click',()=>$('#saleFormWrap').classList.toggle('hidden'));
$('#saleProduct').addEventListener('change',()=>{const p=state.products.find(x=>x.id===Number($('#saleProduct').value));if(p)$('#saleRevenue').value=p.price*Number($('#saleUnits').value||1)}); $('#saleUnits').addEventListener('input',()=>{const p=state.products.find(x=>x.id===Number($('#saleProduct').value));if(p)$('#saleRevenue').value=p.price*Number($('#saleUnits').value||1)});
$('#saleForm').addEventListener('submit',async e=>{e.preventDefault();try{await api('/api/sales',{method:'POST',body:JSON.stringify({productId:Number($('#saleProduct').value),soldOn:$('#saleDate').value,units:Number($('#saleUnits').value),revenue:Number($('#saleRevenue').value)})});toast('Sales tersimpan');await loadSales();await loadDashboard();}catch(err){toast(err.message,false)}});
async function loadRecommendations(){ const d=await api('/api/recommendations'); $('#recGrid').innerHTML=d.recommendations.map(r=>`<div class="rec-card glass"><div class="eyebrow">${r.trend_keyword||'GENERAL'}</div><h4>${r.title}</h4><p>${r.rationale}</p><div class="rec-foot"><span class="priority ${r.priority}">${r.priority} priority</span><button class="ghost" data-rec="${r.id}" data-status="${r.status}">${r.status==='done'?'Completed':'Mark done'}</button></div></div>`).join('')||'<div class="muted">No recommendations yet.</div>'; $$('#recGrid [data-rec]').forEach(b=>b.addEventListener('click',async()=>{await api('/api/recommendations',{method:'PATCH',body:JSON.stringify({id:Number(b.dataset.rec),status:'done'})});toast('Recommendation ditandai selesai');loadRecommendations();loadDashboard();})); }
async function populateTrendSelects(){ const trends=state.trends.length?state.trends:(await api('/api/trends')).trends; $('#expTrend').innerHTML='<option value="">General experiment</option>'+trends.map(t=>`<option value="${t.id}">${t.keyword} — ${Math.round(t.score)}</option>`).join(''); }
$('#showExpForm').addEventListener('click',()=>$('#expFormWrap').classList.toggle('hidden'));
$('#expForm').addEventListener('submit',async e=>{e.preventDefault();try{await api('/api/experiments',{method:'POST',body:JSON.stringify({trendId:$('#expTrend').value||null,productName:$('#expProduct').value,hypothesis:$('#expHypothesis').value,budget:Number($('#expBudget').value),testDays:Number($('#expDays').value),targetUnits:Number($('#expTarget').value)})});toast('Experiment tersimpan');$('#expProduct').value='';$('#expHypothesis').value='';await loadExperiments();}catch(err){toast(err.message,false)}});
async function loadExperiments(){ await populateTrendSelects();const d=await api('/api/experiments'); $('#expList').innerHTML=d.experiments.map(e=>`<div class="exp-card glass"><div class="exp-top"><div><div class="eyebrow">${e.trend_keyword||'GENERAL'}</div><h4>${e.product_name}</h4></div><span class="pill">${e.status}</span></div><p class="muted">${e.hypothesis}</p><div class="exp-meta"><span>Budget ${fmtIDR(e.budget)}</span><span>${e.test_days} days</span><span>Target ${fmtNum(e.target_units)} units</span></div></div>`).join('')||'<div class="muted">No experiment created.</div>'; }
async function loadProfile(){const d=await api('/api/profile');$('#profileName').value=d.business.name;$('#profileCity').value=d.business.city;$('#profileEmail').value=state.user.email;}
$('#profileForm').addEventListener('submit',async e=>{e.preventDefault();try{const d=await api('/api/profile',{method:'PUT',body:JSON.stringify({name:$('#profileName').value,city:$('#profileCity').value})});state.business=d.business;$('#businessName').textContent=d.business.name;toast('Profile tersimpan');}catch(err){toast(err.message,false)}});
loadMe();
